# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 97ca7d8049a9c0867affc173d4e2ae3115c7587d82fb370e2b2ae967cee7a4a68db31e1f865efdc5fb2bbcc5891d1a5902d9731aefa1d5c0d7a6eca299977a56

test:
  secret_key_base: db97184744ce4cc6de9f2b49ea3c7d572f8b5003187ef3f606d0933a02d6d0705dac01564462a90cd66956b2f9965ef113f605ccac17ec36fc9bd8fcffccda2e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
